name: smart_parking_solutions_rest
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

publish_to: none

environment:
  sdk: ">=2.0.0 <=3.0.0"

dependencies:
  conduit: ^2.0.0-b2
  mysql1: ^0.19.0
  #path must be the directory of smart_parking_solutions_common's pubspec.yaml this may not be correct for everybody
  smart_parking_solutions_common:
    path: ../smart_parking_solutions_common
dev_dependencies:
  test: ^1.0.0
  conduit_test: ^2.0.0-b1  
